# Generated by Django 4.0.6 on 2022-08-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentmodel',
            old_name='buildDate',
            new_name='buil_date',
        ),
        migrations.RenameField(
            model_name='weeklyitemmodel',
            old_name='buildDate',
            new_name='build_date',
        ),
        migrations.RenameField(
            model_name='weeklyitemmodel',
            old_name='dueData',
            new_name='due_data',
        ),
    ]
