# Generated by Django 4.0.6 on 2022-08-16 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_weeklyitemmodel_due_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyitemmodel',
            old_name='due_data',
            new_name='due_date',
        ),
    ]
