# Generated by Django 4.0.6 on 2022-08-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_weeklyitemmodel_due_date'),
        ('authin', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestjoin',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.team'),
        ),
    ]
